### ISSUE TITLE
Managed. ReadProcessMemory stuck in infinite loop if process closes during execution

### ISSUE THREAD

**Issue by zaafar** [michel-pi/ProcessMemoryUtilities.Net#6]
**Description**
If the target process (x64 bit) closes while the caller of this library (x64 bit process) is reading the target process memory, [ReadProcessMemory](https://github.com/michel-pi/ProcessMemoryUtilities.Net/blob/e776c2e370518b805149afccf57cf91f0be2dd17/source/ProcessMemoryUtilities.Managed/NativeWrapper.RPM.cs#L67) will get stuck in an infinite while loop. This is because NtReadVirtualMemory over [here](https://github.com/michel-pi/ProcessMemoryUtilities.Net/blob/e776c2e370518b805149afccf57cf91f0be2dd17/source/ProcessMemoryUtilities.Managed/NativeWrapper.RPM.cs#L103) returns `PARTIAL_COPY` rather than `INVALID_HANDLE`.

**Workaround**
The caller can directly use the underlying [NtReadVirtualMemory](https://github.com/michel-pi/ProcessMemoryUtilities.Net/blob/e776c2e370518b805149afccf57cf91f0be2dd17/source/ProcessMemoryUtilities/Native/NtDll.RVM.cs#L22) function and handle the errors himself. Since NtReadVirtualMemory doesn't have any kind of looping in it.

**Expected Behavior**
As a caller I expect the library to not hang in an infinite loop and at some point in time returns the controller to the caller. There can be multiple solutions I (as a dev) can think of (not sure which one would be perfect):
1: Over [here](https://github.com/michel-pi/ProcessMemoryUtilities.Net/blob/e776c2e370518b805149afccf57cf91f0be2dd17/source/ProcessMemoryUtilities.Managed/NativeWrapper.RPM.cs#L119) check if the offset is zero, if yes, error out.
2: Put a limit on the while loop and ask the caller for the limit number.

**Comment by michel-pi** [comment]
Thank you for your detailed issue description!

I am glad you discovered that. I'll check through the code and see where i used such loops.

The `Managed` wrapper was build to handle such things. In my experience, people don't handle the `PartialCopy` at all. So I made sure I handle it.

I will solve that by adding the mentioned check!

**Comment by zaafar** [comment]
tested it, new version is working properly, thanks!!!
