### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by SeanBeansShako** [michel-pi/ProcessMemoryUtilities.Net#7]
hello 
i know my question is stupid but i'll give try as i don't know about this things only i can do edit code or just compile it run
i downloaded a cheat using this bypass ByPh but it's deteced
someone says that " just modify the ByPh class in your esp where it reads the memory and write to the memory.
instead those use the methods from this dll to read and write the memory. " 
so how can i use ur file to be undetected

**Comment by michel-pi** [comment]
This has nothing to do with my project
